"""raw_findings and violations tables

Revision ID: 29c2ac0e6597
Revises:
Create Date: 2026-07-19 07:53:26.280348

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29c2ac0e6597"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_findings",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("ingest_id", sa.String(length=64), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_findings")),
    )
    op.create_index(
        op.f("ix_raw_findings_ingest_id"), "raw_findings", ["ingest_id"], unique=False
    )
    op.create_table(
        "violations",
        sa.Column("violation_id", sa.String(length=64), nullable=False),
        sa.Column("raw_finding_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("policy_id", sa.String(length=256), nullable=False),
        sa.Column("resource_id", sa.String(length=1024), nullable=False),
        sa.Column("resource_id_normalized", sa.String(length=1024), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("compliance_state", sa.String(length=32), nullable=False),
        sa.Column("action_status", sa.String(length=32), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("missing_evidence", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["raw_finding_id"],
            ["raw_findings.id"],
            name=op.f("fk_violations_raw_finding_id_raw_findings"),
        ),
        sa.PrimaryKeyConstraint("violation_id", name=op.f("pk_violations")),
    )
    op.create_index(
        op.f("ix_violations_action_status"),
        "violations",
        ["action_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_violations_policy_id"), "violations", ["policy_id"], unique=False
    )
    op.create_index(
        op.f("ix_violations_resource_id_normalized"),
        "violations",
        ["resource_id_normalized"],
        unique=False,
    )
    op.create_index(
        op.f("ix_violations_severity"), "violations", ["severity"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_violations_severity"), table_name="violations")
    op.drop_index(op.f("ix_violations_resource_id_normalized"), table_name="violations")
    op.drop_index(op.f("ix_violations_policy_id"), table_name="violations")
    op.drop_index(op.f("ix_violations_action_status"), table_name="violations")
    op.drop_table("violations")
    op.drop_index(op.f("ix_raw_findings_ingest_id"), table_name="raw_findings")
    op.drop_table("raw_findings")
    # ### end Alembic commands ###
