"""audit prompt_run_id and evidence_packet

Revision ID: 380983188d8c
Revises: 3a10f3efc10d
Create Date: 2026-07-19 20:51:49.421750

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "380983188d8c"
down_revision: str | Sequence[str] | None = "3a10f3efc10d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audit_events",
        sa.Column(
            "prompt_run_id",
            sa.String(length=32),
            server_default="unknown",
            nullable=False,
        ),
    )
    op.add_column(
        "audit_events",
        sa.Column("evidence_packet", sa.String(length=512), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("audit_events", "evidence_packet")
    op.drop_column("audit_events", "prompt_run_id")
    # ### end Alembic commands ###
