"""action_artifacts table

Revision ID: 7a805285e858
Revises: 7ecc100ab2b6
Create Date: 2026-07-19 16:08:58.784872

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a805285e858"
down_revision: str | Sequence[str] | None = "7ecc100ab2b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action_artifacts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("violation_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("body", sa.String(length=65536), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("approval_state", sa.String(length=16), nullable=False),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["violation_id"],
            ["violations.violation_id"],
            name=op.f("fk_action_artifacts_violation_id_violations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_artifacts")),
    )
    op.create_index(
        op.f("ix_action_artifacts_kind"), "action_artifacts", ["kind"], unique=False
    )
    op.create_index(
        op.f("ix_action_artifacts_violation_id"),
        "action_artifacts",
        ["violation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_action_artifacts_violation_id"), table_name="action_artifacts"
    )
    op.drop_index(op.f("ix_action_artifacts_kind"), table_name="action_artifacts")
    op.drop_table("action_artifacts")
    # ### end Alembic commands ###
