"""approvals table

Revision ID: 7ecc100ab2b6
Revises: 29c2ac0e6597
Create Date: 2026-07-19 14:45:22.781779

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ecc100ab2b6"
down_revision: str | Sequence[str] | None = "29c2ac0e6597"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approvals",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("violation_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("approver_role", sa.String(length=64), nullable=True),
        sa.Column("approver", sa.String(length=128), nullable=True),
        sa.Column("reason", sa.String(length=1024), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["violation_id"],
            ["violations.violation_id"],
            name=op.f("fk_approvals_violation_id_violations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_index(op.f("ix_approvals_status"), "approvals", ["status"], unique=False)
    op.create_index(
        op.f("ix_approvals_violation_id"), "approvals", ["violation_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_approvals_violation_id"), table_name="approvals")
    op.drop_index(op.f("ix_approvals_status"), table_name="approvals")
    op.drop_table("approvals")
    # ### end Alembic commands ###
